package com.ade.fun.cg.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.ade.fun.cg.persistent.SysRolePage;
import com.ade.fun.cg.persistent.SysUser;

/**
 * Class _SysRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SysRole extends CayenneDataObject {

    public static final String ROLE_NAME_PROPERTY = "roleName";
    public static final String ROLE_PAGE_PROPERTY = "rolePage";
    public static final String USER_PROPERTY = "user";

    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setRoleName(String roleName) {
        writeProperty(ROLE_NAME_PROPERTY, roleName);
    }
    public String getRoleName() {
        return (String)readProperty(ROLE_NAME_PROPERTY);
    }

    public void addToRolePage(SysRolePage obj) {
        addToManyTarget(ROLE_PAGE_PROPERTY, obj, true);
    }
    public void removeFromRolePage(SysRolePage obj) {
        removeToManyTarget(ROLE_PAGE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SysRolePage> getRolePage() {
        return (List<SysRolePage>)readProperty(ROLE_PAGE_PROPERTY);
    }


    public void addToUser(SysUser obj) {
        addToManyTarget(USER_PROPERTY, obj, true);
    }
    public void removeFromUser(SysUser obj) {
        removeToManyTarget(USER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SysUser> getUser() {
        return (List<SysUser>)readProperty(USER_PROPERTY);
    }


}
