package com.ade.fun.cg.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.ade.fun.cg.persistent.SysRole;

/**
 * Class _SysUser was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SysUser extends CayenneDataObject {

    public static final String LAST_LOGIN_PROPERTY = "lastLogin";
    public static final String LOCK_MARK_PROPERTY = "lockMark";
    public static final String USER_ACCOUNT_PROPERTY = "userAccount";
    public static final String USER_NAME_PROPERTY = "userName";
    public static final String USER_PASSWORD_PROPERTY = "userPassword";
    public static final String ROLE_PROPERTY = "role";

    public static final String USER_ID_PK_COLUMN = "USER_ID";

    public void setLastLogin(Date lastLogin) {
        writeProperty(LAST_LOGIN_PROPERTY, lastLogin);
    }
    public Date getLastLogin() {
        return (Date)readProperty(LAST_LOGIN_PROPERTY);
    }

    public void setLockMark(Integer lockMark) {
        writeProperty(LOCK_MARK_PROPERTY, lockMark);
    }
    public Integer getLockMark() {
        return (Integer)readProperty(LOCK_MARK_PROPERTY);
    }

    public void setUserAccount(String userAccount) {
        writeProperty(USER_ACCOUNT_PROPERTY, userAccount);
    }
    public String getUserAccount() {
        return (String)readProperty(USER_ACCOUNT_PROPERTY);
    }

    public void setUserName(String userName) {
        writeProperty(USER_NAME_PROPERTY, userName);
    }
    public String getUserName() {
        return (String)readProperty(USER_NAME_PROPERTY);
    }

    public void setUserPassword(String userPassword) {
        writeProperty(USER_PASSWORD_PROPERTY, userPassword);
    }
    public String getUserPassword() {
        return (String)readProperty(USER_PASSWORD_PROPERTY);
    }

    public void setRole(SysRole role) {
        setToOneTarget(ROLE_PROPERTY, role, true);
    }

    public SysRole getRole() {
        return (SysRole)readProperty(ROLE_PROPERTY);
    }


}
