package com.ade.fun.cg.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.ade.fun.cg.persistent.SysRolePage;

/**
 * Class _SysPage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SysPage extends CayenneDataObject {

    public static final String P_ID_PROPERTY = "pId";
    public static final String PAGE_LEVEL_PROPERTY = "pageLevel";
    public static final String PAGE_NAME_PROPERTY = "pageName";
    public static final String PAGE_URL_PROPERTY = "pageUrl";
    public static final String ROLE_PAGE_PROPERTY = "rolePage";

    public static final String PAGE_ID_PK_COLUMN = "PAGE_ID";

    public void setPId(Integer pId) {
        writeProperty(P_ID_PROPERTY, pId);
    }
    public Integer getPId() {
        return (Integer)readProperty(P_ID_PROPERTY);
    }

    public void setPageLevel(Integer pageLevel) {
        writeProperty(PAGE_LEVEL_PROPERTY, pageLevel);
    }
    public Integer getPageLevel() {
        return (Integer)readProperty(PAGE_LEVEL_PROPERTY);
    }

    public void setPageName(String pageName) {
        writeProperty(PAGE_NAME_PROPERTY, pageName);
    }
    public String getPageName() {
        return (String)readProperty(PAGE_NAME_PROPERTY);
    }

    public void setPageUrl(String pageUrl) {
        writeProperty(PAGE_URL_PROPERTY, pageUrl);
    }
    public String getPageUrl() {
        return (String)readProperty(PAGE_URL_PROPERTY);
    }

    public void addToRolePage(SysRolePage obj) {
        addToManyTarget(ROLE_PAGE_PROPERTY, obj, true);
    }
    public void removeFromRolePage(SysRolePage obj) {
        removeToManyTarget(ROLE_PAGE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SysRolePage> getRolePage() {
        return (List<SysRolePage>)readProperty(ROLE_PAGE_PROPERTY);
    }


}
