package com.ade.fun.cg.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

import com.ade.fun.cg.persistent.SysPage;
import com.ade.fun.cg.persistent.SysRole;

/**
 * Class _SysRolePage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SysRolePage extends CayenneDataObject {

    public static final String PAGE_PROPERTY = "page";
    public static final String ROLE_PROPERTY = "role";

    public static final String ROLE_PAGE_ID_PK_COLUMN = "ROLE_PAGE_ID";

    public void setPage(SysPage page) {
        setToOneTarget(PAGE_PROPERTY, page, true);
    }

    public SysPage getPage() {
        return (SysPage)readProperty(PAGE_PROPERTY);
    }


    public void setRole(SysRole role) {
        setToOneTarget(ROLE_PROPERTY, role, true);
    }

    public SysRole getRole() {
        return (SysRole)readProperty(ROLE_PROPERTY);
    }


}
