package com.ade.fun.model.persistent.auto;

import java.util.Map;

import org.apache.cayenne.CayenneDataObject;

import com.ade.fun.model.enumeration.Type;
import com.ade.fun.model.persistent.Character;

/**
 * Class _Account was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Account extends CayenneDataObject {

    public static final String ACCOUNT_CODE_PROPERTY = "accountCode";
    public static final String ACCOUNT_DESC_PROPERTY = "accountDesc";
    public static final String ACCOUNT_TYPE_PROPERTY = "accountType";
    public static final String CHARACTER_PROPERTY = "character";

    public static final String ACCOUNT_ID_PK_COLUMN = "ACCOUNT_ID";

    public void setAccountCode(String accountCode) {
        writeProperty(ACCOUNT_CODE_PROPERTY, accountCode);
    }
    public String getAccountCode() {
        return (String)readProperty(ACCOUNT_CODE_PROPERTY);
    }

    public void setAccountDesc(String accountDesc) {
        writeProperty(ACCOUNT_DESC_PROPERTY, accountDesc);
    }
    public String getAccountDesc() {
        return (String)readProperty(ACCOUNT_DESC_PROPERTY);
    }

    public void setAccountType(Type accountType) {
        writeProperty(ACCOUNT_TYPE_PROPERTY, accountType);
    }
    public Type getAccountType() {
        return (Type)readProperty(ACCOUNT_TYPE_PROPERTY);
    }

    public void addToCharacter(Character obj) {
        addToManyTarget(CHARACTER_PROPERTY, obj, true);
    }
    public void removeFromCharacter(Character obj) {
        removeToManyTarget(CHARACTER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public Map<com.ade.fun.model.enumeration.Position, Character> getCharacter() {
        return (Map<com.ade.fun.model.enumeration.Position, Character>)readProperty(CHARACTER_PROPERTY);
    }


}
