package com.ade.fun.model.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.ade.fun.model.persistent.Occupation;

/**
 * Class _OccupationCategory was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OccupationCategory extends CayenneDataObject {

    public static final String OCCUPATION_CATEGORY_DESC_PROPERTY = "occupationCategoryDesc";
    public static final String OCCUPATION_CATEGORY_NAME_PROPERTY = "occupationCategoryName";
    public static final String OCCUPATION_PROPERTY = "occupation";

    public static final String OCCUPATION_CATEGORY_ID_PK_COLUMN = "OCCUPATION_CATEGORY_ID";

    public void setOccupationCategoryDesc(String occupationCategoryDesc) {
        writeProperty(OCCUPATION_CATEGORY_DESC_PROPERTY, occupationCategoryDesc);
    }
    public String getOccupationCategoryDesc() {
        return (String)readProperty(OCCUPATION_CATEGORY_DESC_PROPERTY);
    }

    public void setOccupationCategoryName(String occupationCategoryName) {
        writeProperty(OCCUPATION_CATEGORY_NAME_PROPERTY, occupationCategoryName);
    }
    public String getOccupationCategoryName() {
        return (String)readProperty(OCCUPATION_CATEGORY_NAME_PROPERTY);
    }

    public void addToOccupation(Occupation obj) {
        addToManyTarget(OCCUPATION_PROPERTY, obj, true);
    }
    public void removeFromOccupation(Occupation obj) {
        removeToManyTarget(OCCUPATION_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Occupation> getOccupation() {
        return (List<Occupation>)readProperty(OCCUPATION_PROPERTY);
    }


}
