package com.ade.fun.model.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.ade.fun.model.persistent.Character;
import com.ade.fun.model.persistent.OccupationCategory;

/**
 * Class _Occupation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Occupation extends CayenneDataObject {

    public static final String OCCUPATION_NAME_PROPERTY = "occupationName";
    public static final String CHARACTER_PROPERTY = "character";
    public static final String OCCUPATION_CATEGORY_PROPERTY = "occupationCategory";

    public static final String OCCUPATION_ID_PK_COLUMN = "OCCUPATION_ID";

    public void setOccupationName(String occupationName) {
        writeProperty(OCCUPATION_NAME_PROPERTY, occupationName);
    }
    public String getOccupationName() {
        return (String)readProperty(OCCUPATION_NAME_PROPERTY);
    }

    public void addToCharacter(Character obj) {
        addToManyTarget(CHARACTER_PROPERTY, obj, true);
    }
    public void removeFromCharacter(Character obj) {
        removeToManyTarget(CHARACTER_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Character> getCharacter() {
        return (List<Character>)readProperty(CHARACTER_PROPERTY);
    }


    public void setOccupationCategory(OccupationCategory occupationCategory) {
        setToOneTarget(OCCUPATION_CATEGORY_PROPERTY, occupationCategory, true);
    }

    public OccupationCategory getOccupationCategory() {
        return (OccupationCategory)readProperty(OCCUPATION_CATEGORY_PROPERTY);
    }


}
